apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: wxk46gf57-go-gitops
  description: This is GitOps manifest for wxk46gf57-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: wxk46gf57-go
    janus-idp.io/tekton: wxk46gf57-go 
    backstage.io/kubernetes-id: wxk46gf57-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:wxk46gf57-go
